In [14]:
import datetime

In [1]:
from datetime import date

In [2]:
today = date.today()
print(today)         # e.g., 2025-09-20
print(today.year)    # 2025
print(today.month)   # 9
print(today.day)     # 20

2025-09-20
2025
9
20


In [16]:
date1 = date(2025,5,20)
print(date1)
print(type(date1))

2025-05-20
<class 'datetime.date'>


In [22]:
date1 = date(2015,9,25)
print(date1)
print(type(date1))

2015-09-25
<class 'datetime.date'>


In [5]:
print(date1.year)

2025


In [6]:
print(date1.month)

9


In [7]:
print(date1.day)

25


In [20]:
current_date = date.today()
print(current_date)

2025-09-20


In [21]:
delta = current_date.year - date1.year
delta

0

In [23]:
delta_month = current_date.month - date1.month
print(delta_month)

0


In [24]:
today = date.today()
print(today)   # e.g., 2025-09-20


2025-09-20


In [27]:
birthdate = date(2000, 5, 15)   # YYYY, MM, DD

In [29]:
if (today.month, today.day) < (birthdate.month, birthdate.day):
    age -= 1

In [54]:
# Age Calculator
from datetime import date
def calculate_age(birthdate):
    today = date.today()
    age = today.year - birthdate.year -((today.month,today.day)<(birthdate.month,birthdate.day))
    return age
def get_birthdate():
    while True:
        try:
            year = int(input("Enter the birth year:"))
            month = int(input("Enter the birth month:"))
            day = int(input("Enter the birth day:"))
            birthdate = date(year,month,day)
            return birthdate
        except ValueError:
            print("Enter valid date please")



In [55]:
def main():
    birthdate = get_birthdate()
    age = calculate_age(birthdate)
    print(f"Your Current Age is: ",age)

In [56]:
if __name__ == "__main__":
    main()

Enter the birth year: 1998
Enter the birth month: 12
Enter the birth day: 30


Your Current Age is:  26


In [2]:
import numpy as np

In [11]:
array1 = np.array([1,2,33,10,20,30])
array1

array([ 1,  2, 33, 10, 20, 30])

In [12]:
array2 = np.array([20,30])
array2

array([20, 30])

In [18]:
array1 = np.array([1,2,33,10,20,30])
array2 = np.array([20,30,5,15,25,35])  # Same size
array3 = array1 + array2
print(array3)
# Output: array([21, 32, 38, 25, 45, 65])

[21 32 38 25 45 65]


In [19]:
array3[3]

np.int64(25)

In [20]:
import numpy as np

In [26]:
import scipy
from scipy.linalg import inv

In [27]:
A = np.array([[10,20],[60,70]])
inv_A = inv(A)
print(A)
print("===")
print(inv_A)

[[10 20]
 [60 70]]
===
[[-0.14  0.04]
 [ 0.12 -0.02]]
